#!/bin/sh
exec tail -n +3 $0

menuentry 'System Rescue CD' {
  load_video
  insmod gzio
  insmod part_gpt
  insmod part_msdos
  insmod ext2
  insmod fat
  search --no-floppy --label SYSRESCUE --set=root
  echo   'Loading Linux kernel ...'
  linux  /SYSRESCCD/BOOT/X86_64/VMLINUZ archisobasedir=sysresccd archisolabel=SYSRESCUE copytoram setkmap=us
  echo   'Loading initramfs ...'
  initrd /SYSRESCCD/BOOT/X86_64/SYSRESCCD.IMG
}

if [ ${grub_platform} == "efi" ]; then
	menuentry "Firmware setup" {
		fwsetup
	}
fi

menuentry "UEFI Shell" {
	insmod fat
	insmod chain
	search --no-floppy --set=root --file /shellx64.efi
	chainloader /shellx64.efi
}

menuentry "System shutdown" {
	halt
}


menuentry "System restart" {
	reboot
}


